environment              = "sandbox"
aws_region               = "eu-west-1"
tfstate_bucket           = "holyport-consulting-sandbox-terraform-state"
tfstate_bucket_region    = "eu-west-2"
serverless_deploy_bucket = "holyport-consulting-sandbox-serverless"
project_name             = "flask"
stage_name               = "sandbox"
